### ISSUE TITLE
but, i think...

### ISSUE THREAD

**Issue by libondev** [Stan-BK/dev-issues#4]

**Comment by libondev** [comment]
No but

**Comment by Stan-BK** [comment]
U got a big problem now

**Comment by libondev** [comment]
Oh damn, I hope this isn't true.

**Comment by libondev** [comment]
Who would have thought that someone would come to dig graves?

**Comment by Stan-BK** [comment]
I just come by and see some weird thing

**Comment by libondev** [comment]
i just "water green box" 🤣
